### ISSUE TITLE
Abstract about Boule and Harmonica for EGU 2021 (Due 20 Jan!)

### ISSUE THREAD

**Issue by leouieda** [fatiando/egu2021#1]
This is a submission for [EGU 2021](https://www.egu21.eu/) to present Boule and Harmonica and solicit contributions. It's being submitted to [this session](https://meetingorganizer.copernicus.org/EGU21/session/39917). I wrote a first pass at the abstract and would welcome any feedback and corrections (feel free to open a PR).

I would like to invite as authors anyone involved in the development and conception of these two packages (not just the coding): @santisoler @dabiged @MarkWieczorek @ioshchepkov @birocoles @aguspesce @nshea3 @craigmillernz @lperozzi 

If any of you would like to be listed as author, please send a pull request adding your name and affiliation to the README so I can include you in the EGU system. We have until **Friday 15 of January** to update the abstract.

The presentation itself will be 2 minutes (not sure if video or text this time) plus a "virtual PICO" which I think means an interactive poster.

**Comment by dabiged** [comment]
The abstract reads well.

This sentence in the first paragraph seems clumsy.

> Much of this confusion likely stems from the lack of widely available tools **for performing the more corrections** needed to arrive at a geophysically meaningful gravity disturbance.

**Comment by lperozzi** [comment]
HI @leouieda. Many thanks for the invitation. The abstract looks very interesting. On my side, I only applied Boule and Harmonica to a dataset in order to compare a classical gravity processing (free-air corrections + 167 km approximation for topography correction)  with the gravity disturbance and prism layer approach using Boule and Harmonica (preprint of the paper is available [here](https://doi.org/10.31223/X52P5T), for those who are interested). However, I've not really participated in the development of Boule or Harmonica, so I'm not sure that I fit as an author for this abstract...

**Comment by leouieda** [comment]
> This sentence in the first paragraph seems clumsy.

Ah that was left over from an edit. I'll more the "more" from that. Thanks for the catch!

> However, I've not really participated in the development of Boule or Harmonica, so I'm not sure that I fit as an author for this abstract... 

@lperozzi I invited you in particular because of the valuable feedback you gave (and are giving) on the prism layer design and other things. So I definitely think you fit as an author but that is entirely up to you 🙂

**Comment by MarkWieczorek** [comment]
Hi. Thanks for the invitation. I'll try to work on this tomorrow (Jan 12). There is an LPSC deadline for me that is taking all of my time.

**Comment by aguspesce** [comment]
Hello.
Thanks for the invitation. I feel something very similar to @lperozzi.
I read the abstract and I think it is very good, I really like the idea to invite other people to the project!
@leouieda  and @santisoler let me know if you need help with the presentation.
Cheers!


-- 
Agustina Pesce
PhD in Geophysics
Postdoc scholarship @ CONICET & Instituto Geofísico Sismológico Volponi,
UNSJ

**Comment by leouieda** [comment]
We have a bit more time now since the deadline was pushed to next week. I'll still submit this week though since the system gets really bad close to the deadline.

For session, I have two options:

1. [ G1.2 Mathematical methods for the analysis of potential field data and geodetic time series](https://meetingorganizer.copernicus.org/EGU21/session/39913): the call is for mathematical and computational advancements in gravimetry and magnetometry in various scales, for Earth and planetary applications. I think we can fit there and I expect to have a more geodetic crowd in that session, which would be good to get feedback on Boule.
2.  [G4.3 Acquisition and processing of gravity and magnetic field data and their integrative interpretation](https://meetingorganizer.copernicus.org/EGU21/session/39917): I'm co-convening this session and @santisoler is presenting there some work on equivalent sources and Harmonica. This would be more of a geophysics crowd but will already hear about Harmonica in Santiago's presentation.

Me and @santisoler were leaning towards G1.2 since that would spread related talks to other sessions and maybe draw in a different crowd. **Does anyone object to that or would rather go for G4.3 instead?** Please let me know **before Friday** since I'm planning on submitting that day.

**Comment by lperozzi** [comment]
Good for me the G1.2

**Comment by aguspesce** [comment]
My opinion is G1.2

**Comment by leouieda** [comment]
Alright, submitted to G1.2 🎉 We can still make changes and add authors until 20 Jan (next week).

**Comment by leouieda** [comment]
The abstract has been accepted and officially published! 🎉  DOI, presentation time and date, etc are in the README.
